export const DEFAULT_MASCOT_ID = "pingo" as const;

export const MASCOT_IDS = [
  "pingo",
  "violet",
  "biscuit",
  "waddle",
  "sparkle",
  "orbit",
  "ember",
  "quacks",
  "momo",
  "buzzwell",
  "sprout",
  "moonbun",
] as const;

export type MascotId = (typeof MASCOT_IDS)[number];

export const MASCOT_PROGRESS_PALETTES = {
  pingo: {
    background: "#FFE1A8",
    foreground: "#6F3A00",
    secondaryText: "#955400",
    track: "#F2B85D",
    fill: "#F28C18",
    ringTrack: "#F3B24F",
    shadow: "#C56A0A",
  },
  violet: {
    background: "#DCD2FF",
    foreground: "#35206C",
    secondaryText: "#5B4294",
    track: "#B9AAF0",
    fill: "#7653E6",
    ringTrack: "#A695E8",
    shadow: "#5438B8",
  },
  biscuit: {
    background: "#EBC89F",
    foreground: "#542F18",
    secondaryText: "#7B4A28",
    track: "#C99A6B",
    fill: "#A9622A",
    ringTrack: "#C28B56",
    shadow: "#75401F",
  },
  waddle: {
    background: "#CED9FF",
    foreground: "#1E3478",
    secondaryText: "#40589A",
    track: "#A8B8ED",
    fill: "#3558B8",
    ringTrack: "#8298DC",
    shadow: "#263F91",
  },
  sparkle: {
    background: "#F8D1E8",
    foreground: "#6E244E",
    secondaryText: "#904066",
    track: "#EAA8CE",
    fill: "#D94F9C",
    ringTrack: "#E687BD",
    shadow: "#A33172",
  },
  orbit: {
    background: "#DAF4A3",
    foreground: "#28550F",
    secondaryText: "#497426",
    track: "#B5DB6F",
    fill: "#63A91D",
    ringTrack: "#91C84A",
    shadow: "#3D7D13",
  },
  ember: {
    background: "#FFCFB4",
    foreground: "#72270E",
    secondaryText: "#963C18",
    track: "#F2A174",
    fill: "#E95A1C",
    ringTrack: "#EF833F",
    shadow: "#A63A12",
  },
  quacks: {
    background: "#FFF0A3",
    foreground: "#634000",
    secondaryText: "#8A6100",
    track: "#E7C95C",
    fill: "#F28C18",
    ringTrack: "#F2C13B",
    shadow: "#A76A00",
  },
  momo: {
    background: "#DFCBF6",
    foreground: "#4D226F",
    secondaryText: "#724394",
    track: "#BEA0DD",
    fill: "#7B3FB4",
    ringTrack: "#A777D0",
    shadow: "#5A2B85",
  },
  buzzwell: {
    background: "#FFE99A",
    foreground: "#26231E",
    secondaryText: "#5C512F",
    track: "#D8BD3A",
    fill: "#2F2B33",
    ringTrack: "#F2C91C",
    shadow: "#26231E",
  },
  sprout: {
    background: "#CFF2AB",
    foreground: "#245628",
    secondaryText: "#3F6D42",
    track: "#A6D979",
    fill: "#48A53C",
    ringTrack: "#76C45F",
    shadow: "#2D7B2C",
  },
  moonbun: {
    background: "#E6D5F5",
    foreground: "#4A2369",
    secondaryText: "#6E4986",
    track: "#C5A7DD",
    fill: "#6F3BB0",
    ringTrack: "#9B6DC7",
    shadow: "#512779",
  },
} as const;

export const MASCOTS = [
  {
    id: "pingo",
    name: "Pingo",
    nameKu: "کاک پینگۆ",
    progressPalette: MASCOT_PROGRESS_PALETTES.pingo,
    source: require("../../assets/images/mascots/pet-pingo.webp"),
    featured: true,
    framed: false,
  },
  {
    id: "violet",
    name: "Violet",
    nameKu: "خانم ڤایۆلێت",
    progressPalette: MASCOT_PROGRESS_PALETTES.violet,
    source: require("../../assets/images/mascots/pet-violet.webp"),
    featured: true,
    framed: false,
  },
  {
    id: "biscuit",
    name: "Sir Biscuit",
    nameKu: "جەنابی بسکیت",
    progressPalette: MASCOT_PROGRESS_PALETTES.biscuit,
    source: require("../../assets/images/mascots/pet-biscuit.webp"),
    featured: false,
    framed: true,
  },
  {
    id: "waddle",
    name: "Captain Waddle",
    nameKu: "کاپتن لەنگۆ",
    progressPalette: MASCOT_PROGRESS_PALETTES.waddle,
    source: require("../../assets/images/mascots/pet-waddle.webp"),
    featured: false,
    framed: true,
  },
  {
    id: "sparkle",
    name: "Dr. Sparkle",
    nameKu: "دکتۆر بریسکە",
    progressPalette: MASCOT_PROGRESS_PALETTES.sparkle,
    source: require("../../assets/images/mascots/pet-sparkle.webp"),
    featured: false,
    framed: true,
  },
  {
    id: "orbit",
    name: "Agent Orbit",
    nameKu: "بریکار گەردوون",
    progressPalette: MASCOT_PROGRESS_PALETTES.orbit,
    source: require("../../assets/images/mascots/pet-orbit.webp"),
    featured: false,
    framed: true,
  },
  {
    id: "ember",
    name: "Sir Ember",
    nameKu: "جەنابی پشکۆ",
    progressPalette: MASCOT_PROGRESS_PALETTES.ember,
    source: require("../../assets/images/mascots/pet-ember.webp"),
    featured: false,
    framed: true,
  },
  {
    id: "quacks",
    name: "Sunny Quacks",
    nameKu: "کاک قاقای خۆرەتاو",
    progressPalette: MASCOT_PROGRESS_PALETTES.quacks,
    source: require("../../assets/images/mascots/pet-quacks.webp"),
    featured: false,
    framed: true,
  },
  {
    id: "momo",
    name: "Professor Momo",
    nameKu: "پڕۆفیسۆر مۆمۆ",
    progressPalette: MASCOT_PROGRESS_PALETTES.momo,
    source: require("../../assets/images/mascots/pet-momo.webp"),
    featured: false,
    framed: true,
  },
  {
    id: "buzzwell",
    name: "Buzzwell",
    nameKu: "ئەندازیار ویزەویز",
    progressPalette: MASCOT_PROGRESS_PALETTES.buzzwell,
    source: require("../../assets/images/mascots/pet-buzzwell.webp"),
    featured: false,
    framed: true,
  },
  {
    id: "sprout",
    name: "Dr. Sprout",
    nameKu: "دکتۆر چیلکە",
    progressPalette: MASCOT_PROGRESS_PALETTES.sprout,
    source: require("../../assets/images/mascots/pet-sprout.webp"),
    featured: false,
    framed: true,
  },
  {
    id: "moonbun",
    name: "Moonbun, Esq.",
    nameKu: "پارێزەر نانی مانگ",
    progressPalette: MASCOT_PROGRESS_PALETTES.moonbun,
    source: require("../../assets/images/mascots/pet-moonbun.webp"),
    featured: false,
    framed: true,
  },
] as const;

export function isMascotId(value: unknown): value is MascotId {
  return typeof value === "string" && MASCOT_IDS.includes(value as MascotId);
}

export function getMascot(id: unknown) {
  return MASCOTS.find((mascot) => mascot.id === id) ?? MASCOTS[0];
}

export function getMascotDisplayName(
  mascot: (typeof MASCOTS)[number],
  locale: string,
) {
  return locale === "ku" ? mascot.nameKu : mascot.name;
}
