export const DEFAULT_MASCOT_ID = "pingo" as const;

export const MASCOT_IDS = [
  "pingo",
  "violet",
  "biscuit",
  "waddle",
  "sparkle",
  "orbit",
  "ember",
  "quacks",
  "momo",
  "buzzwell",
  "sprout",
  "moonbun",
] as const;

export type MascotId = (typeof MASCOT_IDS)[number];

export const MASCOT_PROGRESS_PALETTES = {
  pingo: {
    background: "#A84420",
    foreground: "#FFF9F2",
    secondaryText: "#FFE0CF",
    track: "#71301D",
    fill: "#FFD166",
    ringTrack: "#D97A55",
    shadow: "#71301D",
  },
  violet: {
    background: "#5A3F91",
    foreground: "#FFF9FF",
    secondaryText: "#E8DCF7",
    track: "#3D2A68",
    fill: "#E8A8D1",
    ringTrack: "#876DB7",
    shadow: "#3D2A68",
  },
  biscuit: {
    background: "#765038",
    foreground: "#FFF9F2",
    secondaryText: "#EAD8C9",
    track: "#503525",
    fill: "#F2C078",
    ringTrack: "#A77C5D",
    shadow: "#503525",
  },
  waddle: {
    background: "#28566A",
    foreground: "#F7FCFD",
    secondaryText: "#D3E7EA",
    track: "#193A49",
    fill: "#79D1C5",
    ringTrack: "#5C8797",
    shadow: "#193A49",
  },
  sparkle: {
    background: "#8A3F68",
    foreground: "#FFF8FC",
    secondaryText: "#F2D8E6",
    track: "#5E2946",
    fill: "#F4B3D1",
    ringTrack: "#B87396",
    shadow: "#5E2946",
  },
  orbit: {
    background: "#425B78",
    foreground: "#F8FBFF",
    secondaryText: "#D7E3EF",
    track: "#293A50",
    fill: "#9BC5E6",
    ringTrack: "#748BA5",
    shadow: "#293A50",
  },
  ember: {
    background: "#9B4934",
    foreground: "#FFF9F5",
    secondaryText: "#F3D8CF",
    track: "#672F23",
    fill: "#F4BB72",
    ringTrack: "#C57B66",
    shadow: "#672F23",
  },
  quacks: {
    background: "#6F5A1F",
    foreground: "#FFFBEF",
    secondaryText: "#EEE4BF",
    track: "#493B15",
    fill: "#F1CB52",
    ringTrack: "#9A8547",
    shadow: "#493B15",
  },
  momo: {
    background: "#664A3B",
    foreground: "#FFF9F5",
    secondaryText: "#E8D6CC",
    track: "#443128",
    fill: "#D7A06B",
    ringTrack: "#957363",
    shadow: "#443128",
  },
  buzzwell: {
    background: "#63531D",
    foreground: "#FFFCF0",
    secondaryText: "#EDE3B9",
    track: "#413613",
    fill: "#F2C94C",
    ringTrack: "#8F7D42",
    shadow: "#413613",
  },
  sprout: {
    background: "#356852",
    foreground: "#F6FCF9",
    secondaryText: "#D2E8DE",
    track: "#214737",
    fill: "#8FD3A9",
    ringTrack: "#67957F",
    shadow: "#214737",
  },
  moonbun: {
    background: "#60456E",
    foreground: "#FFF9FF",
    secondaryText: "#E7D9EB",
    track: "#402D4A",
    fill: "#C8A4D7",
    ringTrack: "#8C7198",
    shadow: "#402D4A",
  },
} as const;

export const MASCOTS = [
  {
    id: "pingo",
    name: "Pingo",
    nameKu: "کاک پینگۆ",
    progressPalette: MASCOT_PROGRESS_PALETTES.pingo,
    source: require("../../assets/images/mascots/pet-pingo.webp"),
    featured: true,
    framed: false,
  },
  {
    id: "violet",
    name: "Violet",
    nameKu: "خانم ڤایۆلێت",
    progressPalette: MASCOT_PROGRESS_PALETTES.violet,
    source: require("../../assets/images/mascots/pet-violet.webp"),
    featured: true,
    framed: false,
  },
  {
    id: "biscuit",
    name: "Sir Biscuit",
    nameKu: "جەنابی بسکیت",
    progressPalette: MASCOT_PROGRESS_PALETTES.biscuit,
    source: require("../../assets/images/mascots/pet-biscuit.webp"),
    featured: false,
    framed: true,
  },
  {
    id: "waddle",
    name: "Captain Waddle",
    nameKu: "کاپتن لەنگۆ",
    progressPalette: MASCOT_PROGRESS_PALETTES.waddle,
    source: require("../../assets/images/mascots/pet-waddle.webp"),
    featured: false,
    framed: true,
  },
  {
    id: "sparkle",
    name: "Dr. Sparkle",
    nameKu: "دکتۆر بریسکە",
    progressPalette: MASCOT_PROGRESS_PALETTES.sparkle,
    source: require("../../assets/images/mascots/pet-sparkle.webp"),
    featured: false,
    framed: true,
  },
  {
    id: "orbit",
    name: "Agent Orbit",
    nameKu: "بریکار گەردوون",
    progressPalette: MASCOT_PROGRESS_PALETTES.orbit,
    source: require("../../assets/images/mascots/pet-orbit.webp"),
    featured: false,
    framed: true,
  },
  {
    id: "ember",
    name: "Sir Ember",
    nameKu: "جەنابی پشکۆ",
    progressPalette: MASCOT_PROGRESS_PALETTES.ember,
    source: require("../../assets/images/mascots/pet-ember.webp"),
    featured: false,
    framed: true,
  },
  {
    id: "quacks",
    name: "Sunny Quacks",
    nameKu: "کاک قاقای خۆرەتاو",
    progressPalette: MASCOT_PROGRESS_PALETTES.quacks,
    source: require("../../assets/images/mascots/pet-quacks.webp"),
    featured: false,
    framed: true,
  },
  {
    id: "momo",
    name: "Professor Momo",
    nameKu: "پڕۆفیسۆر مۆمۆ",
    progressPalette: MASCOT_PROGRESS_PALETTES.momo,
    source: require("../../assets/images/mascots/pet-momo.webp"),
    featured: false,
    framed: true,
  },
  {
    id: "buzzwell",
    name: "Buzzwell",
    nameKu: "ئەندازیار ویزەویز",
    progressPalette: MASCOT_PROGRESS_PALETTES.buzzwell,
    source: require("../../assets/images/mascots/pet-buzzwell.webp"),
    featured: false,
    framed: true,
  },
  {
    id: "sprout",
    name: "Dr. Sprout",
    nameKu: "دکتۆر چیلکە",
    progressPalette: MASCOT_PROGRESS_PALETTES.sprout,
    source: require("../../assets/images/mascots/pet-sprout.webp"),
    featured: false,
    framed: true,
  },
  {
    id: "moonbun",
    name: "Moonbun, Esq.",
    nameKu: "پارێزەر نانی مانگ",
    progressPalette: MASCOT_PROGRESS_PALETTES.moonbun,
    source: require("../../assets/images/mascots/pet-moonbun.webp"),
    featured: false,
    framed: true,
  },
] as const;

export function isMascotId(value: unknown): value is MascotId {
  return typeof value === "string" && MASCOT_IDS.includes(value as MascotId);
}

export function getMascot(id: unknown) {
  return MASCOTS.find((mascot) => mascot.id === id) ?? MASCOTS[0];
}

export function getMascotDisplayName(
  mascot: (typeof MASCOTS)[number],
  locale: string,
) {
  return locale === "ku" ? mascot.nameKu : mascot.name;
}
