-- Period leaderboards need immutable XP deltas. The current
-- `user_progress.total_xp` seeds an internal high-water mark so existing
-- accounts keep their full all-time score without pretending that historical
-- XP was earned today or this week.
create table public.leaderboard_xp_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  xp_amount integer not null check (xp_amount > 0),
  source text not null default 'progress_sync',
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

comment on table public.leaderboard_xp_events is
  'Server-written positive XP deltas used for timezone-aware today and week leaderboards.';

create index leaderboard_xp_events_period_idx
  on public.leaderboard_xp_events (occurred_at desc, user_id)
  include (xp_amount);

alter table public.leaderboard_xp_events enable row level security;

create table public.leaderboard_xp_state (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  high_water_total integer not null default 0 check (high_water_total >= 0),
  updated_at timestamptz not null default now()
);

comment on table public.leaderboard_xp_state is
  'Internal high-water mark preventing stale absolute progress syncs from duplicating period XP.';

alter table public.leaderboard_xp_state enable row level security;

-- The ledger is not a client API. Authenticated users receive aggregate rows
-- only through get_leaderboard; service_role retains its normal RLS bypass.
revoke all on table public.leaderboard_xp_events from public, anon, authenticated;
revoke all on sequence public.leaderboard_xp_events_id_seq from public, anon, authenticated;
revoke all on table public.leaderboard_xp_state from public, anon, authenticated;
grant select, insert, update, delete on table public.leaderboard_xp_events to service_role;
grant usage, select on sequence public.leaderboard_xp_events_id_seq to service_role;
grant select, insert, update, delete on table public.leaderboard_xp_state to service_role;

-- Existing totals are the initial high-water marks. They remain visible in
-- all-time rankings but are not assigned a fabricated historical timestamp.
insert into public.leaderboard_xp_state (user_id, high_water_total)
select up.user_id, greatest(up.total_xp, 0)
from public.user_progress up;

create or replace function public.capture_leaderboard_xp_event()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_delta integer := 0;
  v_high_water integer := 0;
  v_baghdad_today date := (now() at time zone 'Asia/Baghdad')::date;
begin
  if tg_op = 'INSERT' then
    insert into public.leaderboard_xp_state as state (user_id, high_water_total)
    values (new.user_id, greatest(coalesce(new.total_xp, 0), 0))
    on conflict (user_id) do update
      set high_water_total = greatest(
            state.high_water_total,
            excluded.high_water_total
          ),
          updated_at = now();

    -- A first sync can contain progress earned before this ledger existed.
    -- Only today's already-tracked daily XP can safely enter a period bucket.
    if new.last_active_date = v_baghdad_today then
      v_delta := least(
        greatest(coalesce(new.daily_xp, 0), 0),
        greatest(coalesce(new.total_xp, 0), 0)
      );
    end if;
  else
    -- Absolute client syncs can arrive out of order across devices. Locking a
    -- separate high-water row means a stale decrease followed by a retry does
    -- not award the same XP twice.
    insert into public.leaderboard_xp_state (user_id, high_water_total)
    values (new.user_id, greatest(coalesce(old.total_xp, 0), 0))
    on conflict (user_id) do nothing;

    select s.high_water_total
    into v_high_water
    from public.leaderboard_xp_state s
    where s.user_id = new.user_id
    for update;

    v_delta := greatest(coalesce(new.total_xp, 0), 0) - v_high_water;

    if v_delta > 0 then
      update public.leaderboard_xp_state
      set high_water_total = greatest(coalesce(new.total_xp, 0), 0),
          updated_at = now()
      where user_id = new.user_id;
    end if;
  end if;

  if v_delta > 0 then
    insert into public.leaderboard_xp_events (user_id, xp_amount, source)
    values (
      new.user_id,
      v_delta,
      case when tg_op = 'INSERT' then 'initial_daily_sync' else 'progress_sync' end
    );
  end if;

  return new;
end;
$$;

revoke all on function public.capture_leaderboard_xp_event() from public, anon, authenticated;

drop trigger if exists capture_leaderboard_xp_event on public.user_progress;
create trigger capture_leaderboard_xp_event
  after insert or update of total_xp on public.user_progress
  for each row execute function public.capture_leaderboard_xp_event();

-- Backfill only XP that the existing schema can place in a real period:
-- today's daily_xp. Older XP stays all-time-only because no trustworthy
-- timestamp exists for it.
insert into public.leaderboard_xp_events (user_id, xp_amount, source)
select
  up.user_id,
  least(greatest(up.daily_xp, 0), greatest(up.total_xp, 0)),
  'migration_daily_backfill'
from public.user_progress up
where up.last_active_date = (now() at time zone 'Asia/Baghdad')::date
  and least(greatest(up.daily_xp, 0), greatest(up.total_xp, 0)) > 0;

-- Replace the one-argument RPC instead of adding an overloaded defaulted
-- function; PostgREST calls that send only p_limit would otherwise be
-- ambiguous. Existing callers remain compatible and default to all time.
drop function if exists public.get_leaderboard(integer);

create function public.get_leaderboard(
  p_limit integer default 50,
  p_period text default 'all',
  p_timezone text default 'Asia/Baghdad'
)
returns table (
  user_id uuid,
  rank bigint,
  display_name text,
  avatar_url text,
  selected_mascot_id text,
  period_xp integer,
  total_xp integer
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_period text := lower(trim(coalesce(p_period, 'all')));
  v_timezone text;
  v_period_start timestamptz;
begin
  if (select auth.uid()) is null
    and coalesce((select auth.jwt() ->> 'role'), '') <> 'service_role'
  then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  select zones.name
  into v_timezone
  from pg_catalog.pg_timezone_names zones
  where zones.name = coalesce(nullif(trim(p_timezone), ''), 'Asia/Baghdad')
  limit 1;

  if v_timezone is null then
    v_timezone := 'Asia/Baghdad';
  end if;

  case v_period
    when 'all' then
      v_period_start := null;
    when 'today' then
      v_period_start := date_trunc('day', now() at time zone v_timezone) at time zone v_timezone;
    when 'week' then
      -- PostgreSQL weeks start on Monday in the learner's validated timezone.
      v_period_start := date_trunc('week', now() at time zone v_timezone) at time zone v_timezone;
    else
      raise exception 'Unsupported leaderboard period: %', p_period
        using errcode = '22023';
  end case;

  return query
  with scores as (
    select
      p.id,
      p.display_name,
      p.avatar_url,
      p.selected_mascot_id,
      p.updated_at,
      greatest(
        coalesce(s.high_water_total, 0),
        coalesce(up.total_xp, 0),
        0
      )::bigint as lifetime_score,
      case
        when v_period = 'all' then greatest(
          coalesce(s.high_water_total, 0),
          coalesce(up.total_xp, 0),
          0
        )::bigint
        else coalesce(sum(e.xp_amount), 0)::bigint
      end as period_score
    from public.profiles p
    left join public.user_progress up on up.user_id = p.id
    left join public.leaderboard_xp_state s on s.user_id = p.id
    left join public.leaderboard_xp_events e
      on v_period <> 'all'
     and e.user_id = p.id
     and e.occurred_at >= v_period_start
    group by
      p.id,
      p.display_name,
      p.avatar_url,
      p.selected_mascot_id,
      p.updated_at,
      up.total_xp,
      s.high_water_total
  ),
  eligible as (
    select *
    from scores
    where v_period = 'all' or period_score > 0
  ),
  ranked as (
    select
      eligible.*,
      row_number() over (
        order by eligible.period_score desc, eligible.lifetime_score desc,
          eligible.updated_at asc, eligible.id
      ) as score_rank
    from eligible
  )
  select
    ranked.id,
    ranked.score_rank,
    coalesce(nullif(trim(ranked.display_name), ''), 'New learner'),
    case
      when ranked.avatar_url ~* '^https?://'
       and ranked.avatar_url !~* '\.svg'
       and ranked.avatar_url !~* '/premade/'
      then ranked.avatar_url
      else null
    end,
    ranked.selected_mascot_id,
    least(ranked.period_score, 2147483647)::integer,
    least(ranked.lifetime_score, 2147483647)::integer
  from ranked
  order by ranked.score_rank
  limit least(greatest(coalesce(p_limit, 50), 1), 100);
end;
$$;

revoke all on function public.get_leaderboard(integer, text, text) from public, anon;
grant execute on function public.get_leaderboard(integer, text, text) to authenticated;
grant execute on function public.get_leaderboard(integer, text, text) to service_role;
